[package]
name = "wadm"
version = "0.4.0"
edition = "2021"

[features]
default = []
cli = ["clap", "tracing-opentelemetry", "tracing-subscriber", "opentelemetry", "opentelemetry-otlp", "atty"]

[dependencies]
anyhow = "1"
async-nats = "0.29"
async-trait = "0.1"
atty = { version = "0.2", optional = true }
bytes = "1"
chrono = "0.4"
clap = { version = "4", features = ["derive", "cargo", "env"], optional = true }
cloudevents-sdk = "0.7"
futures = "0.3"
indexmap = { version = "1", features = ["serde-1"] }
lazy_static = "1"
nkeys = "0.2.0"
# One version back to avoid clashes with 0.10 of otlp
opentelemetry = { version = "0.17", features = ["rt-tokio"], optional = true }
# 0.10 to avoid protoc dep
opentelemetry-otlp = { version = "0.10", features = ["http-proto", "reqwest-client"], optional = true }
# TODO: Actually leverage prometheus
prometheus = { version = "0.13", optional = true }
rand = { version = "0.8", features = ["small_rng"] }
serde = "1"
serde_json = "1"
serde_yaml = "0.9"
sha2 = "0.10.2"
thiserror = "1"
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-futures = "0.2"
tracing-opentelemetry = { version = "0.17", optional = true }
tracing-subscriber = { version = "0.3.7", features = ["env-filter", "json"], optional = true }
uuid = "1"
# Temporary workaround until we can merge and release some fixes to wasmbus that require the use of
# an older version of nats
wasmcloud-control-interface = { version = "0.24", git = "https://github.com/thomastaylor312/control-interface-client.git", branch = "tmp/dep_workaround" }
semver = { version = "1.0.16", features = [ "serde" ] }

[dev-dependencies]
serial_test = "1"

[[bin]]
name = "wadm"
path = "bin/main.rs"
required-features = ["cli"]
